apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine-configmap-and-secret-volume
      image: alpine:3.7
      command: [ "/bin/sh", "-c", "cat /etc/mykey/tls.crt" ]
      command: [ "/bin/sh", "-c", "ls /etc/mykey" ]
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/mykey
      - name: config-map-volume
        mountPath: /etc/mykey/d
  volumes:
    - name: secret-volume
      secret:
        secretName: tlssecret
    - name: config-map-volume
      configMap:
        name: my-data-configmap
  restartPolicy: Neve
