apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine-configmap-volume
      image: alpine:3.7
      command: [ "/bin/sh", "-c", "cat /etc/mykey/tls.crt" ]
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/mykey
  volumes:
    - name: secret-volume
      secret:
        secretName: tlssecret
  restartPolicy: Never
