apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine-configmap-volume
      image: alpine:3.7
      command: [ "/bin/sh", "-c", "ls /etc/mykey" ]
      volumeMounts:
      - name: config-map-volume
        mountPath: /etc/mykey
  volumes:
    - name: config-map-volume
      configMap:
        name: my-data-configmap       
  restartPolicy: Never
