apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox1
    image: busybox
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  - name: busybox2
    image: busybox
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
