apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
        - name: key1
          valueFrom:
            configMapKeyRef:
              name: my-data-configmap
              key: key1 
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
