apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hellocronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hellocronjob
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello I'm scheduled CronJob
          restartPolicy: OnFailure
