apiVersion: v1
kind: PersistentVolume
metadata:
  name: generic-data-pv
spec:
  capacity: 
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/
