apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: nginxsvc
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: ngnix-conf
          mountPath: /etc/nginx
  volumeClaimTemplates:
  - metadata:
      name: generic-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
