apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      ports: 
          - containerPort: 443
          - containerPort: 80
      volumeMounts:
          - name: nginx-secure-vol
            mountPath: /etc/nginx/ssl
      volumeMounts:
          - name: nginx-config-vol
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
  volumes:
    - name: nginx-secure-vol
      secret:
        secretName: tlsecret 
    - name: nginx-config-vol
      configMap:
        name: nginx-secure-config   
