apiVersion: v1
kind: Pod
metadata:
  name: linux-centos-ubuntu
spec:
  containers:
  - name: centos
    image: centos
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  - name: ubutnu
    image: ubuntu
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
