apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kuebernetes-by-example-prod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        env: production
    spec:
      containers:
        - name: hello
          image: 'anishnath/hello:latest'
          ports:
            - containerPort: 8080
          imagePullPolicy: Always  

---
apiVersion: v1
kind: Service
metadata:
  name: kuebernetes-by-example-service
  labels:
    name: kuebernetes-by-example-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    app: hello
  type: LoadBalancer
